os: osx
language: cpp
compiler:
    - g++
before_install:
  - brew --version
  - brew list --versions
install:
  - brew reinstall
      protobuf
  - brew install outofmem0ry/tap/apache-hawq
script: make
