language: c

os:
  - osx

compiler:
  - clang

before_install:
  - brew --version
  - "brew update 2>&1 > /tmp/brew-update.txt || (cat /tmp/brew-update.txt && false)"
  - brew list --versions

install:
  - brew reinstall
      Gsasl
      bison
      ccache
      cpanm
      libevent
      maven
      openssl
      python
      snappy
  - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
  - tar -xzvf protobuf-2.4.1.tar.gz
  - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd
  - brew reinstall
      protobuf-c
      thrift
  - brew outdated libyaml || brew upgrade libyaml
  - brew outdated json-c  || brew upgrade json-c
  - brew outdated boost   || brew upgrade boost
  - brew outdated maven   || brew upgrade maven
  - brew install iproute2mac
  - brew list --versions
  - sudo easy_install pip
  - sudo pip install pycrypto
  - sudo cpanm install JSON
  - brew install outofmem0ry/tap/apache-hawq
